WRAP_CLASS("itk::ComponentTreeLeavesToImageFilter" POINTER)
  FOREACH(t1 ${WRAP_ITK_SCALAR})
    FOREACH(t2 ${WRAP_ITK_USIGN_INT})
      FOREACH(d ${WRAP_ITK_DIMS})
        WRAP_TEMPLATE("${ITKM_CT${t1}${d}UL}${ITKM_I${t2}${d}}" "${ITKT_CT${t1}${d}UL}, ${ITKT_I${t2}${d}}")
        WRAP_TEMPLATE("${ITKM_CT${t1}${d}D}${ITKM_I${t2}${d}}" "${ITKT_CT${t1}${d}D}, ${ITKT_I${t2}${d}}")
      ENDFOREACH(d)
    ENDFOREACH(t2)
  ENDFOREACH(t1)
END_WRAP_CLASS()
