WRAP_INCLUDE("itkIndex.h")

WRAP_CLASS("itk::ComponentTreeNode")
  FOREACH(t ${WRAP_ITK_SCALAR})
#    FOREACH(d ${WRAP_ITK_DIMS})
      WRAP_TEMPLATE("${ITKM_${t}}L${ITKM_UL}" "${ITKT_${t}}, long, ${ITKT_UL}, std::vector< long >")
      WRAP_TEMPLATE("${ITKM_${t}}L${ITKM_D}" "${ITKT_${t}}, long, ${ITKT_D}, std::vector< long >")
#    ENDFOREACH(d)
  ENDFOREACH(t)
END_WRAP_CLASS()