WRAP_CLASS("itk::ComponentTreeAttributeToImageFilter" POINTER)
  FOREACH(t ${WRAP_ITK_SCALAR})
    FOREACH(d ${WRAP_ITK_DIMS})
      WRAP_TEMPLATE("${ITKM_CT${t}${d}UL}${ITKM_IUL${d}}" "${ITKT_CT${t}${d}UL}, ${ITKT_IUL${d}}")
      FOREACH(t2 ${WRAP_ITK_REAL})
        WRAP_TEMPLATE("${ITKM_CT${t}${d}D}${ITKM_I${t2}${d}}" "${ITKT_CT${t}${d}D}, ${ITKT_I${t2}${d}}")
      ENDFOREACH(t2)
    ENDFOREACH(d)
  ENDFOREACH(t)
END_WRAP_CLASS()
