WRAP_INCLUDE("itkIndex.h")

WRAP_CLASS("itk::ComponentTreeNode")
  FOREACH(t ${WRAP_ITK_SCALAR})
#    FOREACH(d ${WRAP_ITK_DIMS})
      WRAP_TEMPLATE("${ITKM_${t}}SL${ITKM_UL}" "${ITKT_${t}}, signed long, ${ITKT_UL}")
      WRAP_TEMPLATE("${ITKM_${t}}SL${ITKM_D}" "${ITKT_${t}}, signed long, ${ITKT_D}")
#    ENDFOREACH(d)
  ENDFOREACH(t)
END_WRAP_CLASS()